<?php

use Illuminate\Database\Seeder;
use Faker\Generator as Faker;

class PanoramaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $roles = array(
            array('lat' => '3.146138', 'lng' => '101.631982', 'tajuk' => 'Lokasi Panorama', 'keterangan' => 'Lorem Ipsum atau Lipsum merupakan satu kaedah atau satu cara yang digunakan dalam penerbitan untuk mempersembahkan elemen grafik dalam sesuatu dokumen dari segi fon, rekabentuk dan rekaletak. Lorem Ipsum juga boleh dijadikan sebagai teks sementara sebelum teks sebenar dimasukkan.', 'gambar_360' => 'panorama_0243.jpg', 'tarikh' => now(), 'created_at' => now(), 'updated_at' => now()),
            array('lat' => '3.146055', 'lng' => '101.632013', 'tajuk' => 'Lokasi Panorama', 'keterangan' => 'Lorem Ipsum atau Lipsum merupakan satu kaedah atau satu cara yang digunakan dalam penerbitan untuk mempersembahkan elemen grafik dalam sesuatu dokumen dari segi fon, rekabentuk dan rekaletak. Lorem Ipsum juga boleh dijadikan sebagai teks sementara sebelum teks sebenar dimasukkan.', 'gambar_360' => 'panorama_0244.jpg', 'tarikh' => now(), 'created_at' => now(), 'updated_at' => now()),
            array('lat' => '3.146548', 'lng' => '101.632477', 'tajuk' => 'Lokasi Panorama', 'keterangan' => 'Lorem Ipsum atau Lipsum merupakan satu kaedah atau satu cara yang digunakan dalam penerbitan untuk mempersembahkan elemen grafik dalam sesuatu dokumen dari segi fon, rekabentuk dan rekaletak. Lorem Ipsum juga boleh dijadikan sebagai teks sementara sebelum teks sebenar dimasukkan.', 'gambar_360' => 'panorama_0248.jpg', 'tarikh' => now(), 'created_at' => now(), 'updated_at' => now()),
            array('lat' => '3.146039', 'lng' => '101.632505', 'tajuk' => 'Lokasi Panorama', 'keterangan' => 'Lorem Ipsum atau Lipsum merupakan satu kaedah atau satu cara yang digunakan dalam penerbitan untuk mempersembahkan elemen grafik dalam sesuatu dokumen dari segi fon, rekabentuk dan rekaletak. Lorem Ipsum juga boleh dijadikan sebagai teks sementara sebelum teks sebenar dimasukkan.', 'gambar_360' => 'panorama_0249.jpg', 'tarikh' => now(), 'created_at' => now(), 'updated_at' => now()),
            array('lat' => '3.147223', 'lng' => '101.631833', 'tajuk' => 'Lokasi Panorama', 'keterangan' => 'Lorem Ipsum atau Lipsum merupakan satu kaedah atau satu cara yang digunakan dalam penerbitan untuk mempersembahkan elemen grafik dalam sesuatu dokumen dari segi fon, rekabentuk dan rekaletak. Lorem Ipsum juga boleh dijadikan sebagai teks sementara sebelum teks sebenar dimasukkan.', 'gambar_360' => 'panorama_0250.jpg', 'tarikh' => now(), 'created_at' => now(), 'updated_at' => now()),
            array('lat' => '3.147952', 'lng' => '101.631910', 'tajuk' => 'Lokasi Panorama', 'keterangan' => 'Lorem Ipsum atau Lipsum merupakan satu kaedah atau satu cara yang digunakan dalam penerbitan untuk mempersembahkan elemen grafik dalam sesuatu dokumen dari segi fon, rekabentuk dan rekaletak. Lorem Ipsum juga boleh dijadikan sebagai teks sementara sebelum teks sebenar dimasukkan.', 'gambar_360' => 'panorama_0251.jpg', 'tarikh' => now(), 'created_at' => now(), 'updated_at' => now()),
            array('lat' => '3.147818', 'lng' => '101.632073', 'tajuk' => 'Lokasi Panorama', 'keterangan' => 'Lorem Ipsum atau Lipsum merupakan satu kaedah atau satu cara yang digunakan dalam penerbitan untuk mempersembahkan elemen grafik dalam sesuatu dokumen dari segi fon, rekabentuk dan rekaletak. Lorem Ipsum juga boleh dijadikan sebagai teks sementara sebelum teks sebenar dimasukkan.', 'gambar_360' => 'panorama_0252.jpg', 'tarikh' => now(), 'created_at' => now(), 'updated_at' => now()),
            array('lat' => '3.149207', 'lng' => '101.632536', 'tajuk' => 'Lokasi Panorama', 'keterangan' => 'Lorem Ipsum atau Lipsum merupakan satu kaedah atau satu cara yang digunakan dalam penerbitan untuk mempersembahkan elemen grafik dalam sesuatu dokumen dari segi fon, rekabentuk dan rekaletak. Lorem Ipsum juga boleh dijadikan sebagai teks sementara sebelum teks sebenar dimasukkan.', 'gambar_360' => 'panorama_0254.jpg', 'tarikh' => now(), 'created_at' => now(), 'updated_at' => now()),
            array('lat' => '3.148984', 'lng' => '101.632466', 'tajuk' => 'Lokasi Panorama', 'keterangan' => 'Lorem Ipsum atau Lipsum merupakan satu kaedah atau satu cara yang digunakan dalam penerbitan untuk mempersembahkan elemen grafik dalam sesuatu dokumen dari segi fon, rekabentuk dan rekaletak. Lorem Ipsum juga boleh dijadikan sebagai teks sementara sebelum teks sebenar dimasukkan.', 'gambar_360' => 'panorama_0256.jpg', 'tarikh' => now(), 'created_at' => now(), 'updated_at' => now()),
            array('lat' => '3.148694', 'lng' => '101.632705', 'tajuk' => 'Lokasi Panorama', 'keterangan' => 'Lorem Ipsum atau Lipsum merupakan satu kaedah atau satu cara yang digunakan dalam penerbitan untuk mempersembahkan elemen grafik dalam sesuatu dokumen dari segi fon, rekabentuk dan rekaletak. Lorem Ipsum juga boleh dijadikan sebagai teks sementara sebelum teks sebenar dimasukkan.', 'gambar_360' => 'panorama_0257.jpg', 'tarikh' => now(), 'created_at' => now(), 'updated_at' => now()),
            array('lat' => '3.149016', 'lng' => '101.632622', 'tajuk' => 'Lokasi Panorama', 'keterangan' => 'Lorem Ipsum atau Lipsum merupakan satu kaedah atau satu cara yang digunakan dalam penerbitan untuk mempersembahkan elemen grafik dalam sesuatu dokumen dari segi fon, rekabentuk dan rekaletak. Lorem Ipsum juga boleh dijadikan sebagai teks sementara sebelum teks sebenar dimasukkan.', 'gambar_360' => 'panorama_0258.jpg', 'tarikh' => now(), 'created_at' => now(), 'updated_at' => now()),
            array('lat' => '3.149135', 'lng' => '101.632388', 'tajuk' => 'Lokasi Panorama', 'keterangan' => 'Lorem Ipsum atau Lipsum merupakan satu kaedah atau satu cara yang digunakan dalam penerbitan untuk mempersembahkan elemen grafik dalam sesuatu dokumen dari segi fon, rekabentuk dan rekaletak. Lorem Ipsum juga boleh dijadikan sebagai teks sementara sebelum teks sebenar dimasukkan.', 'gambar_360' => 'panorama_0259.jpg', 'tarikh' => now(), 'created_at' => now(), 'updated_at' => now()),
            array('lat' => '3.148779', 'lng' => '101.632939', 'tajuk' => 'Lokasi Panorama', 'keterangan' => 'Lorem Ipsum atau Lipsum merupakan satu kaedah atau satu cara yang digunakan dalam penerbitan untuk mempersembahkan elemen grafik dalam sesuatu dokumen dari segi fon, rekabentuk dan rekaletak. Lorem Ipsum juga boleh dijadikan sebagai teks sementara sebelum teks sebenar dimasukkan.', 'gambar_360' => 'panorama_0260.jpg', 'tarikh' => now(), 'created_at' => now(), 'updated_at' => now()),
            array('lat' => '3.148190', 'lng' => '101.632748', 'tajuk' => 'Lokasi Panorama', 'keterangan' => 'Lorem Ipsum atau Lipsum merupakan satu kaedah atau satu cara yang digunakan dalam penerbitan untuk mempersembahkan elemen grafik dalam sesuatu dokumen dari segi fon, rekabentuk dan rekaletak. Lorem Ipsum juga boleh dijadikan sebagai teks sementara sebelum teks sebenar dimasukkan.', 'gambar_360' => 'panorama_0261.jpg', 'tarikh' => now(), 'created_at' => now(), 'updated_at' => now()),
            array('lat' => '3.145919', 'lng' => '101.631666', 'tajuk' => 'Lokasi Panorama', 'keterangan' => 'Lorem Ipsum atau Lipsum merupakan satu kaedah atau satu cara yang digunakan dalam penerbitan untuk mempersembahkan elemen grafik dalam sesuatu dokumen dari segi fon, rekabentuk dan rekaletak. Lorem Ipsum juga boleh dijadikan sebagai teks sementara sebelum teks sebenar dimasukkan.', 'gambar_360' => 'panorama_0262.jpg', 'tarikh' => now(), 'created_at' => now(), 'updated_at' => now())
        );
        DB::table('panorama')->insert($roles);
    }
}
