APP_NAME="Taman Persekutuan Bukit Kiara"
APP_NAME_SHORT="eKiara"
APP_AGENCY="Jabatan Landskap Negara"
APP_AGENCY_SHORT="JLN"
APP_ENV=local
#APP_ENV=production
#APP_KEY=base64:nFUopHBHWCNKI0PPL7X2/os/Zxi26Cu2zNt+hsaIVAk=
APP_DEBUG=true
#APP_URL=https://tpbk.jln.gov.my/
#ASSET_URL=https://tpbk.jln.gov.my/

LOG_CHANNEL=stack

DB_CONNECTION=pgsql
DB_HOST=127.0.0.1
DB_PORT=5432
DB_DATABASE=tpbk
DB_USERNAME=postgres
DB_PASSWORD=admin
DB_SCHEMA_GIS=tpbk

#DB_CONNECTION_GIS=pgsql
#DB_HOST_GIS=127.0.0.1
#DB_PORT_GIS=5432
#DB_DATABASE_GIS=gis
#DB_USERNAME_GIS=postgres
#DB_PASSWORD_GIS=admin
#DB_SCHEMA_GIS=public

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379
REDIS_DB=1

MAIL_ACTIVE=false
MAIL_DRIVER=smtp
MAIL_HOST="postmaster.mygovuc.gov.my"
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS="kpjln@jln.gov.my"
MAIL_FROM_NAME="Ketua Pengarah JLN"
MAIL_NOREPLY_ADDRESS="no-reply@jln.gov.my"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"